services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paskaroot
      MYSQL_DATABASE: calc_data
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"   # vaihda jos 3306 varattu
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -ppaskaroot --silent"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  db_data: